### ISSUE TITLE
选中某条数据回车后下拉框还在，并未收起

### ISSUE THREAD

**Issue by yangyuxingithub** [tianxiangbing/autosearch#2]
autoSearchInitDate('.tourGuideIpt','2',usercode,'#tourGuideId');
function autoSearchInitDate(ipt,type,usercode,hideId){
    var input = $(ipt);
    var autosearch = new AutoSearch();
    autosearch.init({
        input:input ,
        autoShow:false,
        data:function(callback){
            $.post( HOST.interface+"/TicketSale/queryOrgByType",{
                'type': type,
                'content': input.val(),
                'usercode': usercode
            },
            function(result){
                console.log(result);
                var data = result.data;
                callback(data);
            },'json');
        },
        valueObj:hideId,
        filterColumn:['orgName'],
        column:['orgName'],
        valueName:"id",
    });
}

**Comment by tianxiangbing** [comment]
@yangyuxingithub 没有出现你说的这种情况啊，用这里的例子看下会不会出现，[https://tianxiangbing.github.io/autosearch/](https://tianxiangbing.github.io/autosearch/)

**Comment by yangyuxingithub** [comment]
@tianxiangbing 走的ajax请求，是需要再定义enterCallback方法吗？

**Comment by tianxiangbing** [comment]
@yangyuxingithub 
` var input = $('.autosearch2');
		 var autosearch = new AutoSearch();
		 autosearch.init({input:input ,autoShow:false,data:function(callback){
				$.get('data.txt',{key:input.val()},function(result){
		 		callback(result);
		 		},'json');
	 		}
	 	});`
直接用这种就行了
